/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "MINISTERIO DE HACIENDA Y ECONOMÍA",
  "tagline": "Documentación del Proyecto",
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "keywords",
        "content": "docusaurus, documentación, desarrollo"
      }
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    }
  ],
  "scripts": [
    {
      "src": "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4",
      "async": true
    }
  ],
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://your-docusaurus-site.example.com",
  "baseUrl": "/",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "admonitions": {
            "keywords": [
              "note",
              "tip",
              "info",
              "warning",
              "danger"
            ],
            "extendDefaults": true
          }
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "frontend",
        "path": "docs/frontend",
        "routeBasePath": "frontend",
        "sidebarPath": "/home/Johathan29/Getting_Started/sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "backend",
        "path": "docs/backend",
        "routeBasePath": "backend",
        "sidebarPath": "/home/Johathan29/Getting_Started/sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "systems",
        "path": "docs/systems",
        "routeBasePath": "systems",
        "sidebarPath": "/home/Johathan29/Getting_Started/sidebars.js"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "MINISTERIO DE HACIENDA Y ECONOMÍA",
      "logo": {
        "alt": "Logo",
        "src": "img/logo-cupula.svg"
      },
      "items": [
        {
          "to": "/frontend/intro",
          "label": "Frontend",
          "position": "left",
          "activeBaseRegex": "^/frontend/"
        },
        {
          "to": "/backend/intro",
          "label": "Backend",
          "position": "left",
          "activeBaseRegex": "^/backend/"
        },
        {
          "to": "/systems/intro",
          "label": "Systems",
          "position": "left",
          "activeBaseRegex": "^/systems/"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "items": [
            {
              "html": "\n            <a href=\"https://github.com/facebook/docusaurus\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer__link-item w-auto\" >\n              <img src=\"/img/logo-footer.png\" style=\"\" class='w-[15rem] lg:w-[10rem]'/>\n              \n            </a>\n          "
            }
          ],
          "title": null
        },
        {
          "title": "Learn",
          "items": [
            {
              "to": "/frontend/intro",
              "label": "Frontend",
              "activeBaseRegex": "^/frontend/"
            },
            {
              "to": "/backend/intro",
              "label": "Backend",
              "activeBaseRegex": "^/backend/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Help",
              "to": "/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Help",
              "to": "/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Help",
              "to": "/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Full Stack Docs."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
